//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramacionEnBaseDeDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BibliotecaEFEntities : DbContext
    {
        public BibliotecaEFEntities()
            : base("name=BibliotecaEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LibroCorto> LibroCorto { get; set; }
    
        [DbFunction("BibliotecaEFEntities", "LongitudDeTituloEnLibros")]
        public virtual IQueryable<LongitudDeTituloEnLibros_Result> LongitudDeTituloEnLibros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LongitudDeTituloEnLibros_Result>("[BibliotecaEFEntities].[LongitudDeTituloEnLibros]()");
        }
    }
}
